### ISSUE TITLE
Suggestion: Increase Session Time

### ISSUE THREAD

**Issue by TurtleCode84** [TurtleCode84/tracktask#120]
Nobody likes to sign in over and over again to something like this, but nobody wants to leave something signed in somewhere that will never sign out. Or maybe you do, but that's not the point.

What's a good session time? Right now it's 24 hours.

Opinions, please!

**Comment by Quantum-Codes** [comment]
1 month or 2 weeks. 1 week is also too short

**Comment by TurtleCode84** [comment]
> 1 month or 2 weeks. 1 week is also too short

The longer we make this, the harder it will be to recover compromised accounts, and it makes keeping track of recent logins really difficult.

**Comment by Quantum-Codes** [comment]
So try 1 week.. what's the max we can go btw?

**Comment by TurtleCode84** [comment]
We could technically disable expiration altogether, but the problem is that
there's no easy way to log people out, the only way I know of is to change
the global session encryption key, which logs everyone out. I don't think
changing your password logs you out.

**Comment by TurtleCode84** [comment]
Just confirmed that changing account data refreshes your token, but does _not_ log you out. Logging out on one device does not affect any other devices, and I don't think it's possible with this authentication system.

**Comment by TurtleCode84** [comment]
> So try 1 week.

We'll try a week, a lot of people end up relogging-in anyway, and logins from strange IPs will still be noticable.

**Comment by TurtleCode84** [comment]
Done in https://github.com/TurtleCode84/tracktask/commit/2a7e9722f32f22f10721536728bf4c3b2cf918ff.
