### ISSUE TITLE
Styling: Fix Sign up / Login button

### ISSUE THREAD

**Issue by AwesomePotatoCodes** [TurtleCode84/tracktask#123]
The signup page has unstyled buttons, not sure if intentional but it would look better if it matched with the website's CSS.
![image](https://user-images.githubusercontent.com/105654727/205375355-d6b21c1e-031e-494e-9e6a-aa06454c089c.png)

**Comment by TurtleCode84** [comment]
Good idea!

Tasks currently look something like this:
![image](https://user-images.githubusercontent.com/106502718/205419892-bbec9eef-dc38-41c8-87a9-cfc64e219c36.png)

I think styling the buttons to look similar would fit the style better.

**Comment by AwesomePotatoCodes** [comment]
It'd look great on the whole site! Other than that TrackTask seems pretty good :)

**Comment by TurtleCode84** [comment]
Final preview at https://tracktask-ai71k97vs-turtlecode84.vercel.app, implemented into #129
