### ISSUE TITLE
Styling: Different fonts in different text boxes

### ISSUE THREAD

**Issue by AwesomePotatoCodes** [TurtleCode84/tracktask#145]
Name and description text boxes have different fonts.
![image](https://user-images.githubusercontent.com/105654727/212550270-c13a5816-eaf2-4b8a-8be8-c8e7deb640f0.png)

Possibly change one or the other to make them both the same?

**Comment by TurtleCode84** [comment]
Good catch, working on a consistency fix in #147

**Comment by TurtleCode84** [comment]
Fixed in #147
