### ISSUE TITLE
UI suggestions

### ISSUE THREAD

**Issue by Quantum-Codes** [TurtleCode84/tracktask#24]
- [x] Add some margin to navbar items cuz it looks clumped now
- [ ] (maybe) Card view of tasks (similar to Google notes)
- [x] don't showcase full details of the task. Make it like 10 chars and then a "..."
- [x] More space between `<li>` elements in dashboard and
- [x]  maybe enclose `<li>` in rounded boxes 
- [ ] After adding boxes, we may choose custom colors for the boxes showcasing priority/due date closeness?? Or user chooses the color?
- [x] Remove "mark as completed" checkbox when creating a task (move it to edit task section)
- [x] Use `2rem` for margin in navbar mobile
- [x] Dark mode support

Will add some more items while exploring the site

**Comment by TurtleCode84** [comment]
Dark mode is implemented as a part of #154, so as I wrote there I think this issue can be closed as achieving our main goal, which was to perfect our UI and "nice-to-have" features. If we want to revisit the unfinished tasks in the future, we definitely can.
